# Generated by Django 4.0 on 2021-12-13 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='player',
            table='website_player',
        ),
    ]
