# -*- coding: utf-8 -*-
"""Data_scraping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GxiFbkE21ASbA9LkMuIZ0afdeS2UXiuu
"""

pip install requests

pip install bs4

import requests
from bs4 import BeautifulSoup

req = "https://www.spotrac.com/nba/contracts/sort-value/all-time/limit-2000/"

r = requests.get(req)
page = r.text

soup = BeautifulSoup(page,"html.parser")
print(soup.prettify())

soup.table

names = []

for row in soup.table.find_all('tr'):
  header = row.find('td', class_ = 'rank-name player ')
  #print(header)

  if header == None:
    continue

  name = header.find('a', class_ = 'team-name').getText()
  names.append(name)

print(len(names))

import re
c_start_years = []
c_end_years = []
fa_years = []

for row in soup.table.find_all('tr'):
  header = row.find('td', class_ = 'rank-name player ')
  #print(header)

  if header == None:
    continue

  year = header.find_all('div', class_ = 'rank-position')
  
  for y in year:
    x = y.getText().strip().replace('\n', '').replace('|','').replace(' ','')
    if (any(map(str.isdigit, x))):
       x = re.split('-', x)
       c_start_years.append(int(x[0]))

       z = re.split('\(',x[1])
       c_end_years.append(int(z[0]))

       a = z[1].replace(')', '')
       a = re.split('\:',a)
       fa_years.append(int(a[1]))

   # years.append(y.getText())

print(len(c_start_years))
print(len(c_end_years))
print(len(fa_years))

signed_ages = []

for row in soup.table.find_all('tr'):
  header = row.find('td', class_ = 'center small ')

  if header == None:
    continue

  else:
    header = header.getText()
    signed_ages.append(header)

print(len(signed_ages))

values = []

for row in soup.table.find_all('tr'):
  header = row.find('td', class_ = 'right result ')
  #print(header)

  if header == None:
    continue

  value = header.find('span', class_ = 'cap').getText()
  value = value.strip().replace('$','').replace(',','')
  values.append(int(value))

print(len(values))

aa_values = []

for row in soup.table.find_all('tr'):
  header = row.find('td', class_ = 'right ')
  if header == None:
    continue
  
  aa_value = header.getText()
  aa_value = aa_value.replace('\n','').strip().replace('$','').replace(',','')
  aa_values.append(int(aa_value))
  #print(header)

print(len(aa_values))

import pandas as pd

df = pd.DataFrame({'name': names,
                     'contract_start_year': c_start_years,
                     'contract_end_year': c_end_years,
                     'fa_year': fa_years,
                     'signed_age': signed_ages,
                     'values_dollars': values,
                   'aav_dollars': aa_values},
                    columns = ['name','contract_start_year','contract_end_year','fa_year','signed_age','values_dollars','aav_dollars'])

df.to_csv('Contracts.csv')

